src/agents/flow.py
=> chore: Update flow.py

README.md
Current requirements.txt has dependencies (at least in Ubuntu) that are not supported in Python 3.12.
```
Collecting Requests==2.31.0 (from -r requirements.txt (line 6))
Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.0.1
```
=> doc: update README.md with max python version

.pre-commit-config.yaml
Despite the [CVE bogus problem](https://news.ycombinator.com/item?id=37608110), I think that automatic dependency vulnerability scans is of the essence given the rapid pace of change that the field and its libraries experience. The hook added to the PR direclty checks against [safety-db](https://github.com/pyupio/safety-db) for known vulns. This hook is one of the supported hooks in the pre-commit documentation, present [here](https://pre-commit.com/hooks.html) and seems to me like the no brainer solution for implementing a one shot validation when requirements get updated.
For runs at the time of writing, the requirements established for AIOS show no existent vulnerability.
=> [chore]: Adding CVE dependency checks for requirements.txt via pre-commit recommended hooks

src/llm_kernel/llm_classes/model_registry.py
This PR adds the `gpt-4o` model to the model registry in `model_registry.py`. The changes include:
- Added `gpt-4o` to the `MODEL_REGISTRY` dictionary, mapping it to `GPTLLM`.
=> feat: Add gpt-4o model to model registry

README.md, eval.py, main.py, requirements.txt, simulator.py
1. add pip install pyopenagi from both **pypi** and **locally**
2. add workflow for publish openagi package when using git tag and the tag name matches "v*", e.g., git tag v0.0.1, the publishment triggered by github action is shown as:
=> chore: add pyopenagi install from pypi and locally

.github/workflows/publish.yml, pyproject.toml
1. Attempt to release of a beta version of AIOS package
2. Update the github workflow to enable run `publish to PyPI` only when the PR meets the following two conditions
- The PR title contains v*.\*.\*(e.g., v0.0.1) as the stable version (alpha version)or v*.\*.\*.post\* (e.g., v0.0.1.post1)as the development version (beta version)
- The PR has been merged into the main branch
=> v0.0.1.post1

.github/workflows/publish.yml, pyproject.toml
1. Update rules of publish to PyPI only after creating a github tag. 
2. Upload a beta version to PyPI, where the package is currently named as [aios-core](https://pypi.org/project/aios-core/).
=> chore: update rules of publish to PyPI only after creating a github tag

aios/llm_kernel/llm_classes/ollama_llm.py, aios/llm_kernel/llms.py
There are currently two bugs that prevent the ollama mode from running properly
- llm_name judgment error, now all models are judged as vllm, including those with the ollama prefix
- The num_predict parameter is under ollama.Options
The running results after fix are as follows
```bash
(venv) (base) ➜  AIOS git:(main) python eval.py --llm_name ollama/qwen:7b --agents AcademicAgent:1
[🤖ollama/qwen:7b] AIOS LLM successfully loaded.
**** concurrent Execution Statistics Starts ****
[AcademicAgent] Initialized.
[AcademicAgent] The task you need to solve is: Summarize recent advancements in quantum computing from the past five years.
[Scheduler] AcademicAgent is executing.
[🤖ollama/qwen:7b] AcademicAgent is switched to executing.
[AcademicAgent] [[{"name": "arxiv", "arguments": {"query": …
```
=> Fixed aios not working in ollama mode

aios/llm_core/llm_classes/model_registry.py
Thank you for your contribution to AIOS!
Before submitting the pull request, please ensure **the PR meets the following criteria**! This helps improve the efficiency of the review process.
Before submitting your PR, you need to follow the steps below to maintain code quality.
- Use `pip install -r requirements-dev.txt` to install the extra dependencies in requirements-dev.txt for the following checks.
- Use `pre-commit install` to install pre-commit locally before you commit messages. The pre-commit can help correct the style that are added or modified.
Only specific types of PRs will be reviewed. The PR title is prefixed appropriately (i.e., "prefix: description") to indicate the type of change. Please use one of the prefixs as below:
- `feat` Add new features
- `fix`  Fix bugs
- `docs` …
=> fix: correct the json error for gpt4

aios/memory/single_memory.py
```py
def mem_clear(self, agent_id):
self.aid_to_mid.pop(agent_id)
heapq.heappush(agent_id)
```
I search `aid_to_mid`function in AIOS, but there is no such a function. 
and `heapq.heappush` should have two arguments, and the id should be memory_block_id
Based on the mem_alloc function， mem_clear should be
```py
def mem_clear(self, agent_id):
memory_block = self.aid_to_memory.pop(agent_id)
memory_block_id = memory_block['memory_block_id']
heapq.heappush(self.free_memory_blocks, memory_block_id)
```
=> fix memory_clear bug

aios/llm_core/llm_classes/base_llm.py, aios/llm_core/llm_classes/gpt_llm.py, aios/sdk/autogen/adapater.py, aios/sdk/autogen/agent_adapter.py, aios/sdk/autogen/client_adapter.py, aios/utils/id_generator.py, pyopenagi/agents/call_core.py, scripts/aios-autogen/example_aios_autogen_chat.py, scripts/aios-autogen/example_aios_autogen_code.py, scripts/aios-autogen/example_aios_autogen_tool.py, scripts/aios-autogen/example_aios_autogen_twoagent.py
- **Add Autogen Adapter**: Introduce an autogen adapter to allow agents developed with autogen to operate on AIOS, while preserving a usage pattern that closely mirrors autogen. Simply add the line ·prepare_autogen(agent_process_factory: Optional[AgentProcessFactory])` before your autogen code then you can run your code on aios. Examples can be found in the aios/scripts/aios-autogen/ path.
- **Ollama Support Tool Call Like GPT**: This means that when making an Ollama request on AIOS, the tool call mechanism using tool_call_id and the 'tool' role is supported.
(Additional documentation may be provided in future updates.)
=> feat: autogen adapter

agenthub/app/chat/page.tsx, agenthub/components/homepage/Products.tsx
Hardcoded URL leads user using AIOS locally to the live version at https://my.aios.foundation/chat.
Also removed unused entries. Speeds up compilation time
EDIT: I also accidentally included a commit that defaults the agent to @example/academic_agent if no agent is provided as the WebUI does not work without a mention. I’ll separate this into another draft when I come home today, but if someone reviews this early please take this in mind. I plan to write a draft for doing more structured inputting of the chat command instead of using regex to parse after the fact
=> Fixed hardcoded URL to AIOS chat on local environments

aios_config.json
Currently inference is not rate-limited. As a stopgap measure, this PR changes the production endpoint to Gemini
NOTE: GEMINI_API_KEY must be set on production server before merging
=> Change production to Gemini

README.md, agenthub/app/chat/page.tsx, docs/source/get_started/web_quickstart.rst
The current documentation does not cover the web interface in its getting started folder
this will add a file describing the process and common bugs as well as addressing my issue with a reminder in the README file
=> docs: added documentation for web quickstart

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [AIOS Guru](https://gurubase.io/g/aios) to Gurubase. AIOS Guru uses the data from this repo and data from the [docs](https://aios.readthedocs.io/) to answer questions by leveraging the LLM.
In this PR, I showcased the "AIOS Guru", which highlights that AIOS now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable …
=> Introducing AIOS Guru on Gurubase.io

agenthub/public/MentionListV2Light.scss
Bug Fix: Resolved an issue where the mention dropdown was not displaying names properly in the @ agent selection, specifically in light mode.
Root Cause: The dropdown styling was not compatible with the light mode theme, leading to invisible or misaligned text.
Solution: Adjusted CSS styles and ensured compatibility across themes (light and dark modes).
Testing: Verified functionality in both light and dark modes to ensure the dropdown displays names correctly.
=> fix: Resolve mention dropdown issue in @ agent selection for light mode

agenthub/components/homepage/Hero.tsx
Changed the homepage "Get Started" button to a more descriptive label and added documentation link
=> chore: update homepage documentation link

agenthub/lib/env.ts
WebUI is hardcoded to live server. This PR instead uses the localhost kernel server when running in a development environment.
=> fix: use locally hosted kernel in development environments

README.md, agenthub/components/homepage/Hero.tsx
This PR changes the documentation link to point to the new one in README.md and the WebUI homepage.
=> chore: updated documentation link to point to new

runtime/launch_kernel.sh
Hot reloading breaks the entire system because file changes are made while inferencing an agent, this PR simply disables hot reload
=> fix: remove hot reloading

aios/llm_core/cores/local/ollama.py
The following caused the ollama local mode to fail during a normal demo_agent invocation (i.e. the example call).
1) The assert (requiring the name "ollama" within the model_name is unnecessary and actually prevents normal operation). For example using phi3.5:latest in ollama neither has the name ollama in it nor needs that name. Rather than removing it, I've commented it out allowing me to use the phi3.5:latest model. 
2) rather than using the chat_result from line 59, it was using an undefined variable 'response' in two places causing an exception. I have replaced this with chat_result and subsequent test runs shows it to operate as expected.
=> fix: fixed bugs within address_syscall in ollama.py

README.md
Add detailed API keys configuration guide to README, including:
- Basic yaml configuration example
- Link to detailed setup instructions
=> docs: add API keys configuration guide to README

.github/workflows/test_ollama.yml, aios/llm_core/adapter.py, aios/llm_core/local.py, aios/llm_core/strategy.py
- Add OllamaBackend for local LLM support
- Fix environment variable checks in LLMAdapter
- Update test workflow for Ollama integration
1. Add new OllamaBackend class
2. Connect to Ollama server at port 11434
3. Use litellm to handle API calls
- Add Ollama service health check
- Wait for Ollama to start before tests
=> Fix: Add Ollama Support

aios/llm_core/adapter.py, aios/llm_core/local.py, scripts/run_agent.sh
- Fix the gemini model set up issue
- Add more run-agent example scripts
=> fix gemini model set up issue

README.md
- Update News and model card for supporting deepseek
=> add deepseek support

README.md
- Update docs for deepseek support
=> update deepseek docs

runtime/launch.py
=> fix: configuration refresh
