- src/agents/math_agent/math_agent.py
step is getting into the prompt twice, this removes the extra one.
> remove duplicate step being entered into prompt for MathAgent

- CONTRIBUTE.md
- README.md
add instructions of how to contribute to the AIOS project
> doc: add instructions of how to contribute

- .pre-commit-config.yaml
- requirements.txt
- src/llms/llms.py
add pre-commit package and setup configurations
> chore: add pre-commit check

- src/llms/llm_config/bedrock-anthropic-claude3-haiku.json
- src/llms/llm_config/bedrock-anthropic-claude3-sonnet.json
- src/llms/llms.py
This PR adds support for models available on [Amazon Bedrock](https://aws.amazon.com/bedrock/) (Claude only).
> feat: Support Amazon Bedrock-provided models ⛰️

- .gitignore
- src/llms/llms.py
In File llms.py line 155, I think it should raise the Error instead of return the Error.
> [fix] raise Error in llms

- main.py
- src/agents/agent_config/MathAgent.json
- src/agents/agent_factory.py
- src/agents/agent_process.py
- src/agents/base.py
- src/agents/native_agents/math_agent/math_agent.py
- src/agents/native_agents/narrative_agent/narrative_agent.py
- src/agents/native_agents/rec_agent/rec_agent.py
- src/context/simple_context.py
- src/llms/llms.py
- src/scheduler/base.py
- src/scheduler/fifo_scheduler.py
- src/scheduler/rr_scheduler.py
1. add new features of interrupt in round-robin scheduler
2. update logging style
3. refactor the request listener for agent-process
> add new features and update logging style

- src/agents/agent_config/RecAgent.json
> refactor: typo in RecAgent.json

- main.py
- src/agents/agent_factory.py
- src/agents/base.py
- src/llms/llms.py
- src/tools/base.py
1. fix agent request of calling gpt models
> update dev branch

- CONTRIBUTE.md
I found some slight grammatical mistakes in the documentation and I fixed them.
> docs: Corrected gramatical error

- src/command_parser.py
splited_command -> splitted_command
> refactor: update command_parser.py

- README.md
- src/scheduler/rr_scheduler.py
1. set down queue scanning time
2. update README
> refactor: set down queue scanning time

- README.md
- src/llm_kernel/llm_classes/base_llm.py
- src/llm_kernel/llm_classes/gemini_llm.py
- src/llm_kernel/llm_classes/gpt_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/llm_kernel/llm_config/Llama-2-13b-chat-hf.json
- src/llm_kernel/llm_config/Meta-Llama-3-70B-Instruct.json
- src/llm_kernel/llm_config/Meta-Llama-3-8B-Instruct.json
- src/llm_kernel/llm_config/Mistral-7B-Instruct-v0.2.json
- src/llm_kernel/llm_config/Mixtral-8x22B-Instruct-v0.1.json
- src/llm_kernel/llm_config/Mixtral-8x7B-Instruct-v0.1.json
- src/llm_kernel/llm_config/bedrock-anthropic-claude3-haiku.json
- src/llm_kernel/llm_config/bedrock-anthropic-claude3-sonnet.json
- src/llm_kernel/llm_config/gemini-pro.json
- src/llm_kernel/llm_config/gemma-1.1-2b-it.json
- src/llm_kernel/llm_config/gemma-1.1-7b-it.json
- src/llm_kernel/llm_config/gpt-3.5-turbo.json
- src/llm_kernel/llm_config/gpt-4.json
1. remove redundant llm config files
2. update llm name in README
3. clean up unused comments in llm_kernel
> refactor: remove redundant llm config files and update llm name in README

- src/utils/calculator.py
fix the calculation with following two points
1. accumulation_time should be accumulation_time += (agent_turnaround_time. - agent_waiting_time)
2. In sequential execution, only the first request of the agent will wait much longer, as an agent's remaining request will be executed once they have been put into the queue, so only the first element of request_waiting_times and request_turnaround_times should add the accumulated time
> fix: waiting time and turnaround time calculation

- src/llm_kernel/llm_classes/base_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/llm_kernel/llms.py
1. add vllm module for open-sourced llms, currently set the use_vllm as false to disable using vllm
> feat: add vllm module

- src/llm_kernel/llm_classes/base_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/llm_kernel/llms.py
> Revert "feat: add vllm module"

- main.py
- src/context/simple_context.py
- src/llm_kernel/llm_classes/base_llm.py
- src/llm_kernel/llm_classes/bed_rock.py
- src/llm_kernel/llm_classes/gemini_llm.py
- src/llm_kernel/llm_classes/gpt_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/llm_kernel/llms.py
- src/scheduler/base.py
- src/scheduler/fifo_scheduler.py
- src/scheduler/rr_scheduler.py
- src/utils/logger.py
1. attempt replacing multi-thread with multi-process
> feat: replace thread with multi-process

- .gitignore
Add .env to .gitignore to prevent accidental uploads.
> ignore dotenv

- agent_configs/TravelAgent_task.txt
- main.py
This PR adds the TravelAgent task configuration to the AIOS repository. The changes include:
- Updated `main.py` to include the TravelAgent integration.
- Added `TravelAgent_task.txt` in the `agent_configs` directory.
This PR is related to the implementation of TravelAgent in the OpenAGI repository.
> feat: Add TravelAgent

- README.md
- agent_configs/AcademicAgent_task.txt
- agent_configs/CreationAgent_task.txt
- agent_configs/MathAgent_task.txt
- agent_configs/NarrativeAgent_task.txt
- agent_configs/RecAgent_task.txt
- agent_configs/TravelAgent_task.txt
- eval.py
- main.py
- requirements.txt
- simulator.py
- src/llm_kernel/llm_classes/gemini_llm.py
- src/llm_kernel/llm_classes/gpt_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/utils/calculator.py
1. add AcademicAgent with **arxiv** tool calling enabled
- **Task input example** is:
Summarize recent advancements in quantum computing from the past five years.
- **Tool calling example** is:
[AcademicAgent] ***** It starts to call external tools *****
[AcademicAgent] The solution to step 1: It will call the arxiv with the params as {'query': 'quantum computing advancements 2016-2021'}. The tool response is Published: 2007-08-02
Title: An Introduction to Quantum Computing
Authors: Noson S. Yanofsky
Summary: Quantum Computing is a new and exciting field at the intersection of
mathematics, computer science and physics. It concerns a utilization of quantum
mechanics to improve the efficiency of computation. Here we present a gentle
introduction to some of the ideas in quantum computing. …
> feat: add more tool-calling enabled agents

- Dockerfile
- main.py
add Dockerfile to enable build docker container to run AIOS.
Useful commands will be:
1. docker build -t aios . # which will build a docker image named aios from the current folder containing the Dockerfile
2. docker run -it --name aios aios # which will run the container with the interactive terminal
3. docker start aios
4. docker stop aios
5. docker attach aios
> chore: add Dockerfile

- src/llm_kernel/llm_classes/base_llm.py
- src/llm_kernel/llm_classes/ollama_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/llm_kernel/llm_classes/vllm.py
Features added.
1. function calling for open-sourced models (native huggingface, vllm, ollama) is supported.
TO DO:
add prompting mechanisms (ReAct, Reflexion, etc) to stablize the function calling of open-sourced models
> feat: add function calling for open-sourced models 

- main.py
- src/llm_kernel/llm_classes/base_llm.py
- src/llm_kernel/llm_classes/ollama_llm.py
- src/llm_kernel/llm_classes/open_llm.py
- src/llm_kernel/llm_classes/vllm.py
1. add output parser to address token misalignment in huggingface llm
2. fix the issue of short vllm generation output
> fix: add output parsers for huggingface llm

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- main.py
- requirements-dev.txt
- simulator.py
* Add lint CI
* Add ruff pre-commit
* Add requirement-dev.txt
> chore: better lint ci and pre-commit

- aios/README.md
- aios/context/README.md
- aios/llm_kernel/README.md
- aios/llm_kernel/llm_classes/base_llm.py
- aios/llm_kernel/llm_classes/ollama_llm.py
- aios/llm_kernel/llm_classes/open_llm.py
- aios/llm_kernel/llm_classes/vllm.py
- aios/memory/README.md
- aios/storage/README.md
- aios/utils/README.md
- Add output token limit for ollama
- Rename the title of README in subfolders
> feat: add output token limit for ollama

- README.md
- aios/llm_kernel/llm_classes/base_llm.py
- aios/llm_kernel/llm_classes/gemini_llm.py
- aios/llm_kernel/llm_classes/gpt_llm.py
- aios/llm_kernel/llm_classes/model_registry.py
- aios/llm_kernel/llm_classes/open_llm.py
- aios/llm_kernel/llm_classes/vllm.py
- requirements.txt
- Add function calling support of gemini models
- Add more gemini models
- Refactor tool calling response to fit different LLM function calling implementations better
> feat: add function calling support of gemini models

- .github/ISSUE_TEMPLATE/001-bug-report.yml
- .github/PULL_REQUEST_TEMPLATE.md
> docs: add pull request template

- README.md
- main.py
- scripts/eval/gemini.sh
- scripts/eval/gpt4.sh
- scripts/interactive/gemini.sh
- scripts/run/gemini.sh
- scripts/run/ollama_llama2.sh
- scripts/run/ollama_llama3.sh
- Add agent upload/download
- Update README
> feat: add agent upload/download

- requirements.txt
- runtime/exec.py
- runtime/server.py
- **Description:** Adds in a local runtime to run AIOS on in a containerized API environment.
- **Dependencies:** added uvicorn+fastapi support
> feat: created AIOS runtime template

- README.md
- aios/llm_core/llm_classes/model_registry.py
- docs/source/get_started/quickstart.rst
- **Description:** 
- fix invalid link of quickstart
- add more gpt model endpoints
- **Dependencies:** N/A
> fix: invalid link of quickstart

- aios/llm_core/llm_classes/claude_llm.py
- aios/llm_core/llm_classes/model_registry.py
- requirements.txt
This PR introduces the `ClaudeLLM` class, which implements the functionality for interacting with Anthropic's Claude models within the AIOS framework. The class extends `BaseLLMKernel` and provides methods for processing queries, handling tool calls, and formatting messages for the Anthropic API.
Key features of this implementation include:
- Initialization of the Anthropic client for API calls
- Processing of queries using Claude models
- Conversion of messages to the format expected by the Anthropic API
- Parsing of tool calling outputs from model responses
- Comprehensive error handling and logging
The implementation follows the project's contributing guidelines, including proper documentation, type hinting, and code structure.
N/A
This implementation requires the `anthropic` library. …
> feat: add support for claude-3-5-sonnet-20240620

- README.md
A brief update of the readme to include recent milestones of the project.
> docs: updating the readme to include recent milestones of the project

- .github/PULL_REQUEST_TEMPLATE.md
- runtime/exec.py
- runtime/server.py
- **Description:** Add instructions in PULL_REQUEST_TEMPLATE that the pre-commit check should be run locally before committing messages and submit PR
- **Dependencies:** N/A
> chore: add pre-commit as necessity in PR template

- README.md
- pyopenagi/agents/react_agent.py
- **Description:**
- Fix index error in workflow
- Recover README content
- **Dependencies:** N/A
> fix: workflow index error

- .github/workflows/ci.yml
- pyopenagi/agents/agent_factory.py
- pyopenagi/agents/agent_process.py
- pyopenagi/agents/base_agent.py
- pyopenagi/agents/example/academic_agent/agent.py
- pyopenagi/agents/example/creation_agent/agent.py
- pyopenagi/agents/example/math_agent/agent.py
- pyopenagi/agents/example/rec_agent/agent.py
- pyopenagi/agents/example/travel_agent/agent.py
- pyopenagi/agents/react_agent.py
- requirements-dev.txt
- requirements.txt
- **Description:**
- Rm unused queues
- Update github workflow
- **Dependencies:** requirements.txt, requirements-dev.txt
> fix: rm unused queues

- aios/llm_core/llm_classes/model_registry.py
- aios/llm_core/llm_classes/ollama_llm.py
- pyopenagi/agents/base_agent.py
- pyopenagi/agents/example/rec_agent/agent.py
- pyopenagi/agents/react_agent.py
- pyopenagi/tools/imdb/top_movies.py
- add ollama function calling issues when passing tools
- add gpt-4o-mini endpoints
> fix: ollama fc issues

- CONTRIBUTE.md
- aios/llm_core/llm_classes/model_registry.py
minor doc formatting issue & removed outdated gpt4+gemini1.0
> perf: remove excess llm cores

- aios/llm_core/llm_classes/base_llm.py
- aios/llm_core/llm_classes/gemini_llm.py
- aios/llm_core/llm_classes/hf_native_llm.py
- aios/llm_core/llm_classes/ollama_llm.py
- aios/llm_core/llm_classes/vllm.py
- aios/llm_core/llms.py
- pyopenagi/agents/base_agent.py
- pyopenagi/agents/react_agent.py
- pyopenagi/utils/chat_template.py
- fix json decoding error in generating workflow and tool call
> fix: json decoding error in workflow and tool call

- scripts/eval.py
- scripts/eval/gemini.sh
- scripts/eval/gpt4.sh
- scripts/interactive/gemini.sh
- scripts/interactive/gpt4.sh
- scripts/list_agent.py
- scripts/run/gemini.sh
- scripts/run/gpt4.sh
- scripts/run/ollama_llama2.sh
- scripts/run/ollama_llama3.sh
- Move eval.py into the script folder and refactor the eval script
- Add list_agent script
> refactor: eval script and list_agent script

- README.md
add the documentation tag to readme
> docs: add the documentation tag to readme

- pyopenagi/tools/imdb/top_movies.py
- pyopenagi/tools/imdb/top_series.py
- tests/test_tools/test_top_series.py
PR messages
Description: fix the bug of recagent tools and change the test file
Issue: the names of the class are not matched with the json file. # it fixes, if applicable
Dependencies: any dependencies required for this change
> fix: incorrect api name

- README.md
docs: fix the documentation tag color in readme
> docs: fix the documentation tag color in readme

- aios/llm_core/llm_classes/gemini_llm.py
- aios/llm_core/llm_classes/vllm.py
- pyopenagi/agents/base_agent.py
- pyopenagi/agents/react_agent.py
- pyopenagi/tools/stability-ai/sdxl_turbo.py
Original system prompt of generating the workflow contains all the tool details as 
```json
"type": "function",
"function": {
"name": "sdxl_turbo",
"description": "generate images with the given texts",
"parameters": {
"type": "object",
"properties": {
"prompt": {
"type": "string",
"description": "prompt description of the image to be generated"
}
},
"required": [
"prompt"
]
}
}
```
Revise that and keep only the **name** and **description** to shorten the system prompt.
> refactor: revise system prompt for generating workflow in react agent

- main.py
- requirements.txt
- runtime/server.py
- runtime/state.py
Connects and hooks the AIOS code into a functioning self-sufficient server. Transforms from codebase into modular package, which can then be extended into a UI/Shell Interface/Platform package.
> feat: local runtime linked to AIOS

- .github/workflows/ci.yml
- .gitignore
- pyopenagi/agents/base_agent.py
- pyopenagi/agents/example/academic_agent/agent.py
- pyopenagi/agents/example/cocktail_mixlogist/agent.py
- pyopenagi/agents/example/cook_therapist/agent.py
- pyopenagi/agents/example/creation_agent/agent.py
- pyopenagi/agents/example/fashion_stylist/agent.py
- pyopenagi/agents/example/festival_card_designer/agent.py
- pyopenagi/agents/example/fitness_trainer/agent.py
- pyopenagi/agents/example/interior_decorator/agent.py
- pyopenagi/agents/example/language_tutor/agent.py
- pyopenagi/agents/example/logo_creator/agent.py
- pyopenagi/agents/example/meme_creator/agent.py
- pyopenagi/agents/example/story_teller/agent.py
- Fix agent output path
- Bypass ruff check temporarily
- Update .gitignore
> fix agent output path

- .envrc
- agent_repl.py
- snake.py
Thank you for your contribution to AIOS!
Before submitting the pull request, please ensure **the PR meets the following criteria**! This helps improve the efficiency of the review process.
Before submitting your PR, you need to follow the steps below to maintain code quality.
- Use `pip install -r requirements-dev.txt` to install the extra dependencies in requirements-dev.txt for the following checks.
- Use `pre-commit install` to install pre-commit locally before you commit messages. The pre-commit can help correct the style that are added or modified.
Only specific types of PRs will be reviewed. The PR title is prefixed appropriately (i.e., "prefix: description") to indicate the type of change. Please use one of the prefixs as below:
- `feat` Add new features
- `fix`  Fix bugs
- `docs` …
> added repl

- web/agents/agent.ts
- web/app/page.tsx
- web/components/agents/ChatMessage.tsx
- web/lib/env.ts
- web/package-lock.json
- web/package.json
- connects remote ui to globally hosted AIOS
- secures api gateway
> feat: remote ui connection

- web/app/page.tsx
Thank you for your contribution to AIOS!
Before submitting the pull request, please ensure **the PR meets the following criteria**! This helps improve the efficiency of the review process.
Before submitting your PR, you need to follow the steps below to maintain code quality.
- Use `pip install -r requirements-dev.txt` to install the extra dependencies in requirements-dev.txt for the following checks.
- Use `pre-commit install` to install pre-commit locally before you commit messages. The pre-commit can help correct the style that are added or modified.
Only specific types of PRs will be reviewed. The PR title is prefixed appropriately (i.e., "prefix: description") to indicate the type of change. Please use one of the prefixs as below:
- `feat` Add new features
- `fix`  Fix bugs
- `docs` …
> bug: revert main page to modern styling

- .gitignore
- agent_repl.py
- aios/utils/utils.py
- docs/source/agent_developer/agent_database.rst
- pyopenagi/agents/example/transcribe_agent/agent.py
**Description:** adds a tui that's semi functional, way better than the agent_repl we had before.
**Issue:** patches all bugs in agent_repl that prevent it from running under normal conditions
**Dependencies:** pyfzf, getch (both are optional and are dynamically loaded)
> [feat] improved tui

- aios/scheduler/fifo_scheduler.py
- pyopenagi/agents/agent_factory.py
- pyopenagi/agents/agent_process.py
- Fix recycler for agent ID and agent process ID to enable large-scale agents
> fix ID recycler for agent process

- pyopenagi/agents/agent_factory.py
- pyopenagi/manager/manager.py
- Temporarily revert agenthub manager to the latest stable version
- Replace local path to relative path
> revert agenthub manager

- aios/hooks/llm.py
- main.py
**Add an` aios_stater` to start aios more conveniently**
Can be used like:
```python
parser = parse_global_args()
args = parser.parse_args()
with aios_starter(**vars(args)) as (submit_agent, await_agent_execution):
```
> feat: add aios_stater

- .gitattributes
- pyopenagi/agents/example/academic_agent/agent.py
- pyopenagi/agents/example/academic_agent/config.json
- pyopenagi/manager/manager.py
- scripts/refactor_and_upload_agents.py
- Force agent upload with metadata in config.json
- Add .gitattributes
> force agent upload with metadata in config.json

- README.md
Fix the documentation link in README.md
> docs: fix the documentation link

- README.md
- agenthub/lib/env.ts
- launch.py
- pyopenagi/agents/agent_factory.py
- Change the url to be localhost when running locally
> fix localhost url

- aios/sdk/__init__.py
- aios/sdk/adapter.py
- aios/sdk/autogen/adapter.py
- aios/sdk/autogen/agent_adapter.py
- aios/sdk/autogen/client_adapter.py
- aios/sdk/interpreter/adapter.py
- aios/sdk/metagpt/adapter.py
- docs/source/agent_developer/agent_framework/autogen.rst
- docs/source/agent_developer/agent_framework/metagpt.rst
- docs/source/agent_developer/agent_framework/open_interpreter.rst
- scripts/aios-autogen/example_aios_autogen_chat.py
- scripts/aios-autogen/example_aios_autogen_code.py
- scripts/aios-autogen/example_aios_autogen_tool.py
- scripts/aios-autogen/example_aios_autogen_twoagent.py
- scripts/aios-interpreter/example_aios_interpreter.py
- scripts/aios-metagpt/example_aios_metagpt.py
- scripts/aios-metagpt/example_aios_metagpt_di.py
- Modify framework adapter so that other framework will request by `send_request`
- Update doc about adapter
> fix sdk adapter

- aios/utils/commands/launch.py
- pyproject.toml
Add entry point
```tmol 
[project.scripts]
aios = "aios.utils.commands.launch:main"
```
Then run
```shell
$ pip install -e .
```
You can check whether installation success or not through running 
```shell
$ pip show aios-core
```
Then you can run
```
$ aios --llm_name gpt-4o-mini
Welcome to AIOS!
Args: {'llm_name': 'gpt-4o', 'max_gpu_memory': None, 'eval_device': None, 'max_new_tokens': 256, 'agent_log_mode': 'console', 'scheduler_log_mode': 'console', 'llm_kernel_log_mode': 'console', 'use_backend': 'ollama'}
```
> feat: init command interact

- agent_repl.py
- aios/utils/utils.py
- server.py
I don't want to create any breaking changes, so I'm creating this PR with my current changes that attempt to fix agent_repl.py. There is still one small bug that prevents it from runnning but in the interest of time this is submitted now.
> [feat] fixed agent_repl

- pyopenagi/agents/agent_factory.py
- Fix agent ID allocation (Resolved issue: https://github.com/agiresearch/AIOS/issues/275)
> fix agent id allocation

- server.py
- Fix log mode error in the server.py (Resolved issue: https://github.com/agiresearch/AIOS/issues/278)
> fix log mode in server.py

- aios/sdk/autogen/client_adapter.py
fix autogen adapter `raise ERROR` error
> fix: fix Error import error

- agenthub/app/chat/page.tsx
Prevents hanging when no mention is given due to undefined error from parser's inability to find mention. Also renames function "_" to processAgentCommand.
> Fixed no-mention prompting

- pyopenagi/agents/agent_factory.py
Key Changes
New Feature: Added local loading logic in the load_agent_instance method. The method first attempts to import the agent module and class locally. If that fails, it falls back to the remote loading process.
activate_agent Method Update: Attempts to load the agent locally first; if local loading fails, it then downloads and attempts to load the agent.
New Log Message: Provides a warning message to alert users if both local and remote loading fail.
Testing
The new functionality has been tested locally to ensure both local and remote loading processes work correctly.
Type
Feature addition (feat)
Notes
This change does not impact other modules.
> feat(agents): Add local loading support to AgentFactory with fallback mechanism

- README.md
Updated the documentation link to: https://aios-3.gitbook.io/
> Update the documentation link

- agent_repl.py
- aios/hooks/modules/scheduler.py
- aios/hooks/starter.py
- aios/hooks/syscall.py
- aios/hooks/types/scheduler.py
- aios/llm_core/llm_classes/base_llm.py
- aios/llm_core/llm_classes/gemini_llm.py
- aios/llm_core/llm_classes/gpt_llm.py
- aios/llm_core/llm_classes/hf_native_llm.py
- aios/llm_core/llm_classes/vllm.py
- aios/llm_core/llms.py
- aios/llm_cores/providers/api/anthropic.py
- aios/scheduler/base.py
- aios/scheduler/fifo_scheduler.py
- aios/scheduler/rr_scheduler.py
- aios/sdk/autogen/client_adapter.py
- aios/sdk/interpreter/adapter.py
- aios/sdk/metagpt/adapter.py
- aios/tool/manager.py
- aios/utils/utils.py
- experiment/agent/autogen.py
- experiment/agent/interpreter.py
- experiment/agent/metagpt.py
- experiment/gaia/inference.py
- main.py
- pyopenagi/agents/example/seeact_agent/agent.py
- pyopenagi/utils/chat_template.py
- scripts/aios-seeact/README.md
- scripts/aios-seeact/run_seeact.py
- Refactor the code to sync with the docs update
- Abstract the functions in the FIFO and RR scheduler to the Base scheduler class
- Add Request object as the base object for Query (agent-kernel interaction data object) and Message (kernel module interaction)
- Move context manager as the params for BaseLLM so that context switch can be enabled by passing parameters
- TODO:
- Add message mechanisms for agents
- Refactor code for multi-core and LLM router
> refactor code to sync with docs

- README.md
Update links for docs in the README.md
> update links for docs

- launch.py
- server.py
- Fix the params for starting scheduler in launch.py, which fixs the issue https://github.com/agiresearch/AIOS/issues/331
> fix scheduler params for launch.py

- README.md
Update documentation link and add news of v0.2.0
> docs: update documentation link and add news of v0.2.0

- README.md
Update README to add a better description for AIOS
> docs: update README to add a better description for AIOS

- README.md
- Add the v0.2.0.beta tag for installation from source
- TODO: fix issues in installation from install.sh and update installation guide
> add v0.2.0.beta tag for installation and update README

- agenthub/lib/env.ts
- aios/hooks/modules/agent.py
- Fix the url for agent manager to download agents
> update url for agenthub

- README.md
update readme to revise the introduction of aios
> docs: update readme to revise the introduction of aios

- README.md
- aios/utils/__init__.py
- aios/utils/commands/launch.py
- install/install.sh
- Add API key list display for both 'aios env list' and 'aios env set' commands
- Update README.md with available API keys (OPENAI_API_KEY, GEMINI_API_KEY, HF_HOME)
- Add Required API Key column in LLM model table
> feat: enhance API key documentation and display

- README.md
- aios/llm_core/cores/api/anthropic.py
- runtime/kernel.py
- Add exception messages of API routers in the kernel.py
- Fixed issue: https://github.com/agiresearch/AIOS/issues/365 
- Fix anthropic model messages
- Update README
> Add exception messages

- runtime/kernel.py
- runtime/launch_kernel.sh
- Add CORS support for remote kernel
> add cors for launching kernel

- README.md
docs: update README for v0.2.0.beta release
> docs: update README for v0.2.0.beta release

- .github/workflows/test.yml
test: update the testing workflow to enable automated testing of PRs
> test: update the testing workflow to enable automated testing of PRs

- README.md
- Fix the display issue of different modes of AIOS
> fix: the display issue of different modes of AIOS

- runtime/kernel.py
Fix the indent error in kernel.py
> fix indent in kernel.py

- aios/llm_core/adapter.py
Re-add google compatibility fix
> fix: add google compatibility fix

- README.md
- aios/config/config.yaml.example
- aios/llm_core/adapter.py
- aios/llm_core/local.py
- scripts/run_agent.sh
Fix the tool calling of ollama models
- Enable tools as parameters
- Fix the ollama model's output to completions.choices[0].message.content
> fix tool call of ollama models

- README.md
Added a few lines on running the kernel in detail which may be unfamiliar to non-Unix savvy people. This is a redo of a previous pull request.
> [feat] added detailed kernel running instructions

- README.md
- aios/core/syscall/storage.py
- aios/hooks/syscall.py
- aios/storage/filesystem/lsfs.py
- aios/storage/filesystem/vector_db.py
- aios/storage/storage.py
- requirements.txt
- runtime/kernel.py
- scripts/run_terminal.py
Integrate LLM-based semantic filesystem as a **Terminal UI** for users to interact with, which enables prompt-driven file management, including the following features. 
**Please do not merge after all the following TODOs are done**: 
TODO:
> feat: integrate semantic filesystem

- README.md
- aios/core/syscall/storage.py
- aios/hooks/syscall.py
- aios/storage/filesystem/lsfs.py
- aios/storage/filesystem/vector_db.py
- requirements.txt
- runtime/kernel.py
- scripts/run_terminal.py
> feat: add file lock over file operations and fix redis issue

- aios/memory/base.py
- aios/memory/single_memory.py
feat: Add vector memory manager with ChromaDB integration
A vector memory manager class is added to handle memory operations using ChromaDB. This feature enables:
- Efficient storage and retrieval of memory embeddings 
- Semantic search capabilities
- Clear memory management interface
Key changes:
- Added VectorMemoryManager class with ChromaDB backend
- Implemented memory operations (write/read/clear)
- Added vector embedding generation using LLM
- Included metadata tracking for memory items
The memory manager integrates with the existing BaseMemoryManager interface.
No documentation updates needed as the implementation follows existing patterns.
Testing completed:
- Basic memory operations
- Vector similarity search
- Memory cleanup
> Add vector memory system

- tests/api_test.py
Thank you for your contribution to AIOS!  
Before submitting the pull request, please **make sure to read and follow requirements below and then you can replace all the texts with your own messages**. This helps improve the efficiency of the review process.
When adding new features or updating existing functions, please review the documentation to determine if any changes are required. If so, ensure that the documentation is updated accordingly. The source code for the documentation is located at: https://github.com/agiresearch/AIOS/tree/main/docs. Instructions for writing documentation can be found here: https://github.com/agiresearch/AIOS/blob/main/docs/README.md.
Only specific types of PRs will be reviewed. The PR title is prefixed appropriately (i.e., "prefix: description") to …
> add api_test to generate more test cases

- aios/config/config.yaml.example
- aios/context/simple_context.py
- aios/hooks/modules/scheduler.py
- aios/hooks/types/llm.py
- aios/llm_core/adapter.py
- aios/llm_core/utils.py
- aios/scheduler/fifo_scheduler.py
- aios/scheduler/rr_scheduler.py
- aios/syscall/syscall.py
- aios/tool/manager.py
- aios/utils/logger.py
- runtime/launch.py
- Fix context switch and logger
- Add config.yaml.example to show examples of how to setup config.yaml
> fix context switch and logger

- aios/config/config.yaml
- aios/context/simple_context.py
- aios/llm_core/adapter.py
- aios/llm_core/utils.py
- aios/scheduler/rr_scheduler.py
- aios/syscall/syscall.py
- aios/tool/manager.py
- runtime/launch.py
- runtime/run_terminal.py
- update litellm completion apis and fix launch of AIOS terminal
> update litellm completion apis and fix launch of AIOS terminal

- scripts/run_terminal.py
- update apis for launching LSFS terminal
> update apis for launching LSFS terminal

- aios/llm_core/adapter.py
- aios/llm_core/utils.py
- aios/syscall/syscall.py
- scripts/run_terminal.py
- add patch for fixing LSFS apis
> add patch for fixing LSFS apis

- aios/config/config.yaml
- aios/memory/base.py
- aios/syscall/syscall.py
- runtime/launch.py
Thank you for your contribution to AIOS!  
Before submitting the pull request, please **make sure to read and follow requirements below and then you can replace all the texts with your own messages**. This helps improve the efficiency of the review process.
When adding new features or updating existing functions, please review the documentation to determine if any changes are required. If so, ensure that the documentation is updated accordingly. The source code for the documentation is located at: https://github.com/agiresearch/AIOS/tree/main/docs. Instructions for writing documentation can be found here: https://github.com/agiresearch/AIOS/blob/main/docs/README.md.
Only specific types of PRs will be reviewed. The PR title is prefixed appropriately (i.e., "prefix: description") to …
> initial commit

- README.md
- update uv installation guide in README https://github.com/agiresearch/AIOS/issues/471
> update uv installation guide in README

- .github/workflows/test_ollama.yml
- README.md
- aios/config/config.yaml
- aios/context/simple_context.py
- aios/llm_core/adapter.py
- aios/llm_core/local.py
- aios/llm_core/strategy.py
- aios/llm_core/utils.py
- requirements.txt
- tests/modules/llm/test_ollama.py
- tests/modules/llm/test_openai.py
- tests/modules/memory/test_memory.py
- fix hf model tool calling and test scripts
> fix: hf model tool calling and test scripts

- aios/hooks/modules/agent.py
- aios/hooks/stores/processes.py
- aios/llm_core/adapter.py
- aios/llm_core/strategy.py
- runtime/launch.py
- scripts/run_agent.sh
- Fix agent submit proxy
- Update LLM routing strategy
> fix agent submit proxy

- aios/storage/filesystem/lsfs.py
- aios/storage/storage.py
- tests/modules/storage/storage_api_test.py
- add test script and debug storage module
> add test script and debug storage module

- aios/config/config.yaml.example
- aios/context/simple_context.py
- aios/llm_core/adapter.py
- aios/llm_core/utils.py
- scripts/launch_sglang.sh
- Fix tool call decoding for sglang as backend
> fix tool call decoding for sglang as backend

- aios/llm_core/adapter.py
- runtime/launch.py
- scripts/launch_sglang.sh
- scripts/launch_vllm.sh
- Fix sglang tool calling response format
> fix: sglang tool calling response format

- aios/llm_core/adapter.py
- aios/scheduler/fifo_scheduler.py
- aios/scheduler/rr_scheduler.py
- fix tool call decoding of litellm completion response
> fix tool call decoding of litellm completion response

- runtime/launch.py
- update model selection logic
> update model selection logic

- .github/workflows/cancel-workflow.yml
- .github/workflows/test-ollama.yml
- aios/config/config.yaml
- requirements.txt
- tests/modules/llm/ollama/test_single.py
- fix duplicate github action after merging
> fix duplicate github action after merging

- README.md
- aios/config/config.yaml
- aios/config/config.yaml.example
- aios/llm_core/adapter.py
- runtime/launch.py
- tests/modules/llm/ollama/test_concurrent.py
> update model selection
